# Generated by Django 3.2.5 on 2021-07-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accounttype',
            new_name='type',
        ),
    ]
