# Generated by Django 3.2.5 on 2021-07-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_accounttype_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='acctype',
        ),
    ]
